// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRXKm9rz8eyEWssv6NFcDsDDwb9iTv0hc',
    appId: '1:183108945189:web:9aa4254bb5ac53a66b46cc',
    messagingSenderId: '183108945189',
    projectId: 'my-task-e1a1e',
    authDomain: 'my-task-e1a1e.firebaseapp.com',
    storageBucket: 'my-task-e1a1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRtkHvcEMpOZoKqqAjk-rzchxYvbrNg_s',
    appId: '1:183108945189:android:9425c6037d753fe66b46cc',
    messagingSenderId: '183108945189',
    projectId: 'my-task-e1a1e',
    storageBucket: 'my-task-e1a1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADlhco8E9LISLALQBQtOqA6wyyOORXAys',
    appId: '1:183108945189:ios:83ae606d8e4bf51e6b46cc',
    messagingSenderId: '183108945189',
    projectId: 'my-task-e1a1e',
    storageBucket: 'my-task-e1a1e.appspot.com',
    iosClientId: '183108945189-f7j1fohpi3gh0ee04629b3nnctbgnrk0.apps.googleusercontent.com',
    iosBundleId: 'com.simplon.mytask1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADlhco8E9LISLALQBQtOqA6wyyOORXAys',
    appId: '1:183108945189:ios:83ae606d8e4bf51e6b46cc',
    messagingSenderId: '183108945189',
    projectId: 'my-task-e1a1e',
    storageBucket: 'my-task-e1a1e.appspot.com',
    iosClientId: '183108945189-f7j1fohpi3gh0ee04629b3nnctbgnrk0.apps.googleusercontent.com',
    iosBundleId: 'com.simplon.mytask1',
  );
}
